#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_3DMainMenuPawn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InputCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.ExecuteUbergraph_BP_3DMainMenuPawn
// 0x0340 (0x0340 - 0x0000)
struct BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_InputAxisEvent_AxisValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue;                          // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_InputActionEvent_Key;                       // 0x0010(0x0018)(HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x002C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0040(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0048(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0054(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller;            // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_DeprojectMousePositionToWorld_WorldLocation; // 0x0074(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_DeprojectMousePositionToWorld_WorldDirection; // 0x0080(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DeprojectMousePositionToWorld_ReturnValue; // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0090(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x009C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_Conv_InterfaceToObject_ReturnValue;       // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue_1;              // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_Conv_InterfaceToObject_ReturnValue_1;     // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller_1;          // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D2[0x6];                                       // 0x00D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_InputActionEvent_Key_1;                     // 0x00D8(0x0018)(HasGetValueTypeHash)
	struct FKey                                   K2Node_InputActionEvent_Key_2;                     // 0x00F0(0x0018)(HasGetValueTypeHash)
	float                                         K2Node_InputAxisEvent_AxisValue_2;                 // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_InputAxisEvent_AxisValue_1;                 // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue_1;                        // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue_2;                        // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_2;         // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_3;         // 0x011A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_4;         // 0x011B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11C[0x4];                                      // 0x011C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Button_C*                           K2Node_DynamicCast_AsBP_Button;                    // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x012A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12B[0x5];                                      // 0x012B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_HostButtun_C*>               CallFunc_GetAllActorsOfClass_OutActors;            // 0x0130(0x0010)(ReferenceParm)
	class ABP_HostButtun_C*                       CallFunc_Array_Get_Item;                           // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Button_C*                           K2Node_DynamicCast_AsBP_Button_1;                  // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0151(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0152(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_153[0x5];                                      // 0x0153(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_InputActionEvent_Key_3;                     // 0x0158(0x0018)(HasGetValueTypeHash)
	class ABP_Button_C*                           K2Node_DynamicCast_AsBP_Button_2;                  // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x017A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_17B[0x5];                                      // 0x017B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Button_C*                           K2Node_DynamicCast_AsBP_Button_3;                  // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0189(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x018A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18B[0x5];                                      // 0x018B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Button_C*                           K2Node_DynamicCast_AsBP_Button_4;                  // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19A[0x6];                                      // 0x019A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Button_C*                           K2Node_Select_Default;                             // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_InputActionEvent_Key_4;                     // 0x01B0(0x0018)(HasGetValueTypeHash)
	class ABP_Button_C*                           K2Node_DynamicCast_AsBP_Button_5;                  // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_13;                   // 0x01D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D2[0x6];                                      // 0x01D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Button_C*                           K2Node_Select_Default_1;                           // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_14;                   // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E1[0x7];                                      // 0x01E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_InputActionEvent_Key_5;                     // 0x01E8(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0202(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0203(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_204[0x4];                                      // 0x0204(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0208(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0218(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x02A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x02A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x02A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A7[0x1];                                      // 0x02A7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x02A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x02AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x02B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x02BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x02C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x02D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x02F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0304(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0308(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0314(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Clickable_C>      K2Node_DynamicCast_AsBPI_Clickable;                // 0x0328(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0339(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn");
static_assert(sizeof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn) == 0x000340, "Wrong size on BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, EntryPoint) == 0x000000, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputAxisEvent_AxisValue) == 0x000004, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputAxisEvent_AxisValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Abs_ReturnValue) == 0x000008, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Abs_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Greater_FloatFloat_ReturnValue) == 0x00000C, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, Temp_bool_Variable) == 0x00000D, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputActionEvent_Key) == 0x000010, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputActionEvent_Key' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, Temp_bool_Variable_1) == 0x000028, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_CreateDelegate_OutputDelegate) == 0x00002C, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000040, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000048, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_Event_DeltaSeconds) == 0x000050, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000054, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_GetController_ReturnValue) == 0x000060, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsPlayer_Controller) == 0x000068, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsPlayer_Controller' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_DeprojectMousePositionToWorld_WorldLocation) == 0x000074, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_DeprojectMousePositionToWorld_WorldLocation' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_DeprojectMousePositionToWorld_WorldDirection) == 0x000080, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_DeprojectMousePositionToWorld_WorldDirection' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_DeprojectMousePositionToWorld_ReturnValue) == 0x00008C, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_DeprojectMousePositionToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000090, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Add_VectorVector_ReturnValue) == 0x00009C, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Conv_InterfaceToObject_ReturnValue) == 0x0000A8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Conv_InterfaceToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue) == 0x0000B0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_1) == 0x0000B1, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_GetController_ReturnValue_1) == 0x0000B8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_GetController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Conv_InterfaceToObject_ReturnValue_1) == 0x0000C0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Conv_InterfaceToObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsPlayer_Controller_1) == 0x0000C8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsPlayer_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_1) == 0x0000D0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_2) == 0x0000D1, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputActionEvent_Key_1) == 0x0000D8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputActionEvent_Key_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputActionEvent_Key_2) == 0x0000F0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputActionEvent_Key_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputAxisEvent_AxisValue_2) == 0x000108, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputAxisEvent_AxisValue_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputAxisEvent_AxisValue_1) == 0x00010C, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputAxisEvent_AxisValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Abs_ReturnValue_1) == 0x000110, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Abs_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Abs_ReturnValue_2) == 0x000114, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Abs_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000118, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Greater_FloatFloat_ReturnValue_2) == 0x000119, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Greater_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Greater_FloatFloat_ReturnValue_3) == 0x00011A, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Greater_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Greater_FloatFloat_ReturnValue_4) == 0x00011B, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Greater_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBP_Button) == 0x000120, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBP_Button' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_2) == 0x000128, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_3) == 0x000129, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_4) == 0x00012A, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_GetAllActorsOfClass_OutActors) == 0x000130, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Array_Get_Item) == 0x000140, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBP_Button_1) == 0x000148, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBP_Button_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_3) == 0x000150, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_5) == 0x000151, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_6) == 0x000152, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputActionEvent_Key_3) == 0x000158, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputActionEvent_Key_3' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBP_Button_2) == 0x000170, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBP_Button_2' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_4) == 0x000178, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_7) == 0x000179, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_8) == 0x00017A, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBP_Button_3) == 0x000180, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBP_Button_3' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_5) == 0x000188, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_9) == 0x000189, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_10) == 0x00018A, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBP_Button_4) == 0x000190, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBP_Button_4' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_6) == 0x000198, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_11) == 0x000199, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_Select_Default) == 0x0001A0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_12) == 0x0001A8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputActionEvent_Key_4) == 0x0001B0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputActionEvent_Key_4' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBP_Button_5) == 0x0001C8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBP_Button_5' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_7) == 0x0001D0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_13) == 0x0001D1, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_Select_Default_1) == 0x0001D8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_IsValid_ReturnValue_14) == 0x0001E0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_IsValid_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_InputActionEvent_Key_5) == 0x0001E8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_InputActionEvent_Key_5' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Not_PreBool_ReturnValue) == 0x000200, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_Not_PreBool_ReturnValue_1) == 0x000201, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BooleanAND_ReturnValue) == 0x000202, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BooleanAND_ReturnValue_1) == 0x000203, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, Temp_object_Variable) == 0x000208, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_LineTraceSingle_OutHit) == 0x000218, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_LineTraceSingle_ReturnValue) == 0x0002A4, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_bBlockingHit) == 0x0002A5, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_bInitialOverlap) == 0x0002A6, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_Time) == 0x0002A8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_Distance) == 0x0002AC, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_Location) == 0x0002B0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_ImpactPoint) == 0x0002BC, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_Normal) == 0x0002C8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_ImpactNormal) == 0x0002D4, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_PhysMat) == 0x0002E0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_HitActor) == 0x0002E8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_HitComponent) == 0x0002F0, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_HitBoneName) == 0x0002F8, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_HitItem) == 0x000300, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_FaceIndex) == 0x000304, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_TraceStart) == 0x000308, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BreakHitResult_TraceEnd) == 0x000314, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000320, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_AsBPI_Clickable) == 0x000328, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_AsBPI_Clickable' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, K2Node_DynamicCast_bSuccess_8) == 0x000338, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn, CallFunc_BooleanAND_ReturnValue_2) == 0x000339, "Member 'BP_3DMainMenuPawn_C_ExecuteUbergraph_BP_3DMainMenuPawn::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2
// 0x0004 (0x0004 - 0x0000)
struct BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2 final
{
public:
	float                                         AxisValue;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2) == 0x000004, "Wrong alignment on BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2) == 0x000004, "Wrong size on BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2, AxisValue) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpAxisEvt_MouseMovement_K2Node_InputAxisEvent_2::AxisValue' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1
// 0x0004 (0x0004 - 0x0000)
struct BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1 final
{
public:
	float                                         AxisValue;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1) == 0x000004, "Wrong alignment on BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1) == 0x000004, "Wrong size on BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1, AxisValue) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpAxisEvt_MenuVertical_K2Node_InputAxisEvent_1::AxisValue' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0
// 0x0004 (0x0004 - 0x0000)
struct BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0 final
{
public:
	float                                         AxisValue;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0) == 0x000004, "Wrong alignment on BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0) == 0x000004, "Wrong size on BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0, AxisValue) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpAxisEvt_MenuHorizontal_K2Node_InputAxisEvent_0::AxisValue' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_3DMainMenuPawn_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_3DMainMenuPawn_C_ReceiveTick");
static_assert(sizeof(BP_3DMainMenuPawn_C_ReceiveTick) == 0x000004, "Wrong size on BP_3DMainMenuPawn_C_ReceiveTick");
static_assert(offsetof(BP_3DMainMenuPawn_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_3DMainMenuPawn_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpActEvt_MouseFocus_K2Node_InputActionEvent_0
// 0x0018 (0x0018 - 0x0000)
struct BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0) == 0x000018, "Wrong size on BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0, Key) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpActEvt_MouseFocus_K2Node_InputActionEvent_0::Key' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpActEvt_MenuRight_K2Node_InputActionEvent_1
// 0x0018 (0x0018 - 0x0000)
struct BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1) == 0x000018, "Wrong size on BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1, Key) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpActEvt_MenuRight_K2Node_InputActionEvent_1::Key' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpActEvt_MenuLeft_K2Node_InputActionEvent_2
// 0x0018 (0x0018 - 0x0000)
struct BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2) == 0x000018, "Wrong size on BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2, Key) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpActEvt_MenuLeft_K2Node_InputActionEvent_2::Key' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpActEvt_MenuDown_K2Node_InputActionEvent_3
// 0x0018 (0x0018 - 0x0000)
struct BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3) == 0x000018, "Wrong size on BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3, Key) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpActEvt_MenuDown_K2Node_InputActionEvent_3::Key' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpActEvt_MenuUp_K2Node_InputActionEvent_4
// 0x0018 (0x0018 - 0x0000)
struct BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4) == 0x000018, "Wrong size on BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4, Key) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpActEvt_MenuUp_K2Node_InputActionEvent_4::Key' has a wrong offset!");

// Function BP_3DMainMenuPawn.BP_3DMainMenuPawn_C.InpActEvt_SelectPiece_K2Node_InputActionEvent_5
// 0x0018 (0x0018 - 0x0000)
struct BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5) == 0x000008, "Wrong alignment on BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5");
static_assert(sizeof(BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5) == 0x000018, "Wrong size on BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5");
static_assert(offsetof(BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5, Key) == 0x000000, "Member 'BP_3DMainMenuPawn_C_InpActEvt_SelectPiece_K2Node_InputActionEvent_5::Key' has a wrong offset!");

}

