#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rook

#include "Basic.hpp"

#include "BP_Rook_classes.hpp"


namespace SDK
{

// Function BP_Rook.BP_Rook_C.NewFunction_0
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Rook_C::NewFunction_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rook_C", "NewFunction_0");

	UObject::ProcessEvent(Func, nullptr);
}

}

