#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShateredScreen

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_ShateredScreen.BP_ShateredScreen_C.ExecuteUbergraph_BP_ShateredScreen
// 0x0010 (0x0010 - 0x0000)
struct BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen) == 0x000004, "Wrong alignment on BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen");
static_assert(sizeof(BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen) == 0x000010, "Wrong size on BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen");
static_assert(offsetof(BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen, EntryPoint) == 0x000000, "Member 'BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000004, "Member 'BP_ShateredScreen_C_ExecuteUbergraph_BP_ShateredScreen::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");

}

