#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BSideKingAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BSideKingAnimBP.BSideKingAnimBP_C.ExecuteUbergraph_BSideKingAnimBP
// 0x0068 (0x0068 - 0x0000)
struct BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1; // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_1;       // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_2;       // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_3;       // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2; // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_4;       // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_3; // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_5;       // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x002F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BSideKingChar_C*                    K2Node_DynamicCast_AsBP_BSide_King_Char;           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsFalling_ReturnValue;                    // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Select_Default;                             // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_VSizeXY_ReturnValue;                      // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP) == 0x000008, "Wrong alignment on BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP");
static_assert(sizeof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP) == 0x000068, "Wrong size on BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, EntryPoint) == 0x000000, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue) == 0x000004, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1) == 0x000008, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x00000C, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_LessEqual_FloatFloat_ReturnValue_1) == 0x00000D, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_LessEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue) == 0x000010, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_LessEqual_FloatFloat_ReturnValue_2) == 0x000014, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_LessEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_Not_PreBool_ReturnValue) == 0x000015, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_BooleanAND_ReturnValue) == 0x000016, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_BooleanAND_ReturnValue_1) == 0x000017, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1) == 0x000018, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_GetInstanceAssetPlayerTimeFromEnd_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_LessEqual_FloatFloat_ReturnValue_3) == 0x00001C, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_LessEqual_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2) == 0x000020, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_BooleanAND_ReturnValue_2) == 0x000024, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_LessEqual_FloatFloat_ReturnValue_4) == 0x000025, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_LessEqual_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_3) == 0x000028, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_LessEqual_FloatFloat_ReturnValue_5) == 0x00002C, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_LessEqual_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_Not_PreBool_ReturnValue_1) == 0x00002D, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, Temp_bool_Variable) == 0x00002E, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_BooleanAND_ReturnValue_3) == 0x00002F, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000030, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000034, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, K2Node_Event_DeltaTimeX) == 0x000038, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000040, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, K2Node_DynamicCast_AsBP_BSide_King_Char) == 0x000048, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::K2Node_DynamicCast_AsBP_BSide_King_Char' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_IsValid_ReturnValue) == 0x000051, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_IsFalling_ReturnValue) == 0x000052, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_IsFalling_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, K2Node_Select_Default) == 0x000053, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_VSizeXY_ReturnValue) == 0x000054, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_VSizeXY_ReturnValue' has a wrong offset!");
static_assert(offsetof(BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000058, "Member 'BSideKingAnimBP_C_ExecuteUbergraph_BSideKingAnimBP::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");

// Function BSideKingAnimBP.BSideKingAnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct BSideKingAnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BSideKingAnimBP_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on BSideKingAnimBP_C_BlueprintUpdateAnimation");
static_assert(sizeof(BSideKingAnimBP_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on BSideKingAnimBP_C_BlueprintUpdateAnimation");
static_assert(offsetof(BSideKingAnimBP_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'BSideKingAnimBP_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function BSideKingAnimBP.BSideKingAnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct BSideKingAnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(BSideKingAnimBP_C_AnimGraph) == 0x000008, "Wrong alignment on BSideKingAnimBP_C_AnimGraph");
static_assert(sizeof(BSideKingAnimBP_C_AnimGraph) == 0x000010, "Wrong size on BSideKingAnimBP_C_AnimGraph");
static_assert(offsetof(BSideKingAnimBP_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'BSideKingAnimBP_C_AnimGraph::AnimGraph_0' has a wrong offset!");

}

