#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CopyPose

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass CopyPose.CopyPose_C
// 0x0220 (0x04E0 - 0x02C0)
class UCopyPose_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x02F8(0x01D8)(ContainsInstancedReference)
	class USkeletalMeshComponent*                 Weapon;                                            // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CopyPose(int32 EntryPoint);
	void BlueprintBeginPlay();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CopyPose_C">();
	}
	static class UCopyPose_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCopyPose_C>();
	}
};
static_assert(alignof(UCopyPose_C) == 0x000010, "Wrong alignment on UCopyPose_C");
static_assert(sizeof(UCopyPose_C) == 0x0004E0, "Wrong size on UCopyPose_C");
static_assert(offsetof(UCopyPose_C, UberGraphFrame) == 0x0002C0, "Member 'UCopyPose_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCopyPose_C, AnimGraphNode_Root) == 0x0002C8, "Member 'UCopyPose_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UCopyPose_C, AnimGraphNode_CopyPoseFromMesh) == 0x0002F8, "Member 'UCopyPose_C::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");
static_assert(offsetof(UCopyPose_C, Weapon) == 0x0004D0, "Member 'UCopyPose_C::Weapon' has a wrong offset!");

}

