#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EndScreen

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function EndScreen.EndScreen_C.ExecuteUbergraph_EndScreen
// 0x0090 (0x0090 - 0x0000)
struct EndScreen_C_ExecuteUbergraph_EndScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0028(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0050(0x0028)()
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue;               // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsStandalone_ReturnValue;                 // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(EndScreen_C_ExecuteUbergraph_EndScreen) == 0x000008, "Wrong alignment on EndScreen_C_ExecuteUbergraph_EndScreen");
static_assert(sizeof(EndScreen_C_ExecuteUbergraph_EndScreen) == 0x000090, "Wrong size on EndScreen_C_ExecuteUbergraph_EndScreen");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, EntryPoint) == 0x000000, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, K2Node_MakeStruct_SlateColor) == 0x000028, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, K2Node_MakeStruct_SlateColor_1) == 0x000050, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, CallFunc_GetPlayerController_ReturnValue) == 0x000078, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, CallFunc_DestroySession_ReturnValue) == 0x000080, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::CallFunc_DestroySession_ReturnValue' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, CallFunc_IsValid_ReturnValue) == 0x000088, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(EndScreen_C_ExecuteUbergraph_EndScreen, CallFunc_IsStandalone_ReturnValue) == 0x000089, "Member 'EndScreen_C_ExecuteUbergraph_EndScreen::CallFunc_IsStandalone_ReturnValue' has a wrong offset!");

}

