#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ErrorType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ErrorType.ErrorType
// NumValues: 0x0005
enum class ErrorType : uint8
{
	NewEnumerator3                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	ErrorType_MAX                            = 4,
};

}

