#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPSChessGameInstance

#include "Basic.hpp"

#include "FPSChessGameInstance_classes.hpp"
#include "FPSChessGameInstance_parameters.hpp"


namespace SDK
{

// Function FPSChessGameInstance.FPSChessGameInstance_C.ExecuteUbergraph_FPSChessGameInstance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFPSChessGameInstance_C::ExecuteUbergraph_FPSChessGameInstance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ExecuteUbergraph_FPSChessGameInstance");

	Params::FPSChessGameInstance_C_ExecuteUbergraph_FPSChessGameInstance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.ReceiveInit
// (Event, Public, BlueprintEvent)

void UFPSChessGameInstance_C::ReceiveInit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ReceiveInit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.ChangeChatEnabledEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ChatEnabled                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UFPSChessGameInstance_C::ChangeChatEnabledEvent(bool ChatEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ChangeChatEnabledEvent");

	Params::FPSChessGameInstance_C_ChangeChatEnabledEvent Parms{};

	Parms.ChatEnabled = ChatEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.ChangeSensitivityScopedEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Sensitivity                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFPSChessGameInstance_C::ChangeSensitivityScopedEvent(float Sensitivity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ChangeSensitivityScopedEvent");

	Params::FPSChessGameInstance_C_ChangeSensitivityScopedEvent Parms{};

	Parms.Sensitivity = Sensitivity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.ChangeInvertYEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InvertY                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UFPSChessGameInstance_C::ChangeInvertYEvent(bool InvertY)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ChangeInvertYEvent");

	Params::FPSChessGameInstance_C_ChangeInvertYEvent Parms{};

	Parms.InvertY = InvertY;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.RematchGame
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void UFPSChessGameInstance_C::RematchGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "RematchGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.ReceiveShutdown
// (Event, Public, BlueprintEvent)

void UFPSChessGameInstance_C::ReceiveShutdown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ReceiveShutdown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.HandleNetworkError
// (Event, Public, BlueprintEvent)
// Parameters:
// ENetworkFailure                         FailureType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsServer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UFPSChessGameInstance_C::HandleNetworkError(ENetworkFailure FailureType, bool bIsServer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "HandleNetworkError");

	Params::FPSChessGameInstance_C_HandleNetworkError Parms{};

	Parms.FailureType = FailureType;
	Parms.bIsServer = bIsServer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.ChangeSensitivityEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Sensitivity                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Player2                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UFPSChessGameInstance_C::ChangeSensitivityEvent(float Sensitivity, bool Player2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "ChangeSensitivityEvent");

	Params::FPSChessGameInstance_C_ChangeSensitivityEvent Parms{};

	Parms.Sensitivity = Sensitivity;
	Parms.Player2 = Player2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnSessionInviteAccepted
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// int32                                   LocalPlayerNum                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FBPUniqueNetId                   PersonInvited                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FBlueprintSessionResult          SessionToJoin                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UFPSChessGameInstance_C::OnSessionInviteAccepted(int32 LocalPlayerNum, const struct FBPUniqueNetId& PersonInvited, const struct FBlueprintSessionResult& SessionToJoin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnSessionInviteAccepted");

	Params::FPSChessGameInstance_C_OnSessionInviteAccepted Parms{};

	Parms.LocalPlayerNum = LocalPlayerNum;
	Parms.PersonInvited = std::move(PersonInvited);
	Parms.SessionToJoin = std::move(SessionToJoin);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnSessionInviteReceived
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// int32                                   LocalPlayerNum                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FBPUniqueNetId                   PersonInviting                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// class FString                           AppId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FBlueprintSessionResult          SessionToJoin                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UFPSChessGameInstance_C::OnSessionInviteReceived(int32 LocalPlayerNum, const struct FBPUniqueNetId& PersonInviting, const class FString& AppId, const struct FBlueprintSessionResult& SessionToJoin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnSessionInviteReceived");

	Params::FPSChessGameInstance_C_OnSessionInviteReceived Parms{};

	Parms.LocalPlayerNum = LocalPlayerNum;
	Parms.PersonInviting = std::move(PersonInviting);
	Parms.AppId = std::move(AppId);
	Parms.SessionToJoin = std::move(SessionToJoin);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.JoinGame
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBlueprintSessionResult          Session                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// class UUMG_Session_C*                   UMGSession                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CheckFull                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    LAN                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UFPSChessGameInstance_C::JoinGame(const struct FBlueprintSessionResult& Session, class UUMG_Session_C* UMGSession, bool CheckFull, bool LAN)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "JoinGame");

	Params::FPSChessGameInstance_C_JoinGame Parms{};

	Parms.Session = std::move(Session);
	Parms.UMGSession = UMGSession;
	Parms.CheckFull = CheckFull;
	Parms.LAN = LAN;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.HostGame
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isLAN_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FString                           RoomName_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           Desciption                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    PasswordProtected_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FString                           Password                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UFPSChessGameInstance_C::HostGame(bool isLAN_0, const class FString& RoomName_0, const class FString& Desciption, bool PasswordProtected_0, const class FString& Password)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "HostGame");

	Params::FPSChessGameInstance_C_HostGame Parms{};

	Parms.isLAN_0 = isLAN_0;
	Parms.RoomName_0 = std::move(RoomName_0);
	Parms.Desciption = std::move(Desciption);
	Parms.PasswordProtected_0 = PasswordProtected_0;
	Parms.Password = std::move(Password);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnSuccess_5083F3354C593952FDE933BE08129C41
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBlueprintSessionResult>  Results                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UFPSChessGameInstance_C::OnSuccess_5083F3354C593952FDE933BE08129C41(const TArray<struct FBlueprintSessionResult>& Results)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnSuccess_5083F3354C593952FDE933BE08129C41");

	Params::FPSChessGameInstance_C_OnSuccess_5083F3354C593952FDE933BE08129C41 Parms{};

	Parms.Results = std::move(Results);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnFailure_5083F3354C593952FDE933BE08129C41
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBlueprintSessionResult>  Results                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UFPSChessGameInstance_C::OnFailure_5083F3354C593952FDE933BE08129C41(const TArray<struct FBlueprintSessionResult>& Results)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnFailure_5083F3354C593952FDE933BE08129C41");

	Params::FPSChessGameInstance_C_OnFailure_5083F3354C593952FDE933BE08129C41 Parms{};

	Parms.Results = std::move(Results);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnSuccess_0E679B8D440EAE38D8F3D8934BC522C1
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBlueprintSessionResult>  Results                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UFPSChessGameInstance_C::OnSuccess_0E679B8D440EAE38D8F3D8934BC522C1(const TArray<struct FBlueprintSessionResult>& Results)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnSuccess_0E679B8D440EAE38D8F3D8934BC522C1");

	Params::FPSChessGameInstance_C_OnSuccess_0E679B8D440EAE38D8F3D8934BC522C1 Parms{};

	Parms.Results = std::move(Results);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnFailure_0E679B8D440EAE38D8F3D8934BC522C1
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBlueprintSessionResult>  Results                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UFPSChessGameInstance_C::OnFailure_0E679B8D440EAE38D8F3D8934BC522C1(const TArray<struct FBlueprintSessionResult>& Results)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnFailure_0E679B8D440EAE38D8F3D8934BC522C1");

	Params::FPSChessGameInstance_C_OnFailure_0E679B8D440EAE38D8F3D8934BC522C1 Parms{};

	Parms.Results = std::move(Results);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnSuccess_66C4EA7F4AAAF12C9093359DE0169AE3
// (BlueprintCallable, BlueprintEvent)

void UFPSChessGameInstance_C::OnSuccess_66C4EA7F4AAAF12C9093359DE0169AE3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnSuccess_66C4EA7F4AAAF12C9093359DE0169AE3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnFailure_66C4EA7F4AAAF12C9093359DE0169AE3
// (BlueprintCallable, BlueprintEvent)

void UFPSChessGameInstance_C::OnFailure_66C4EA7F4AAAF12C9093359DE0169AE3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnFailure_66C4EA7F4AAAF12C9093359DE0169AE3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnSuccess_2B0637A340EFC1DAA86D669057CD3134
// (BlueprintCallable, BlueprintEvent)

void UFPSChessGameInstance_C::OnSuccess_2B0637A340EFC1DAA86D669057CD3134()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnSuccess_2B0637A340EFC1DAA86D669057CD3134");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPSChessGameInstance.FPSChessGameInstance_C.OnFailure_2B0637A340EFC1DAA86D669057CD3134
// (BlueprintCallable, BlueprintEvent)

void UFPSChessGameInstance_C::OnFailure_2B0637A340EFC1DAA86D669057CD3134()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPSChessGameInstance_C", "OnFailure_2B0637A340EFC1DAA86D669057CD3134");

	UObject::ProcessEvent(Func, nullptr);
}

}

