#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KillcamInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KillcamInterface.KillcamInterface_C
// 0x0000 (0x0028 - 0x0028)
class IKillcamInterface_C final : public IInterface
{
public:
	void InitAsReplayActor();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KillcamInterface_C">();
	}
	static class IKillcamInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IKillcamInterface_C>();
	}
};
static_assert(alignof(IKillcamInterface_C) == 0x000008, "Wrong alignment on IKillcamInterface_C");
static_assert(sizeof(IKillcamInterface_C) == 0x000028, "Wrong size on IKillcamInterface_C");

}

