#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_ChatMessage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UMG_ChatMessage.UMG_ChatMessage_C
// 0x0020 (0x0280 - 0x0260)
class UUMG_ChatMessage_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UTextBlock*                             ChatMessage;                                       // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             PlayerName;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          isPlayer1;                                         // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UMG_ChatMessage(int32 EntryPoint);
	void CopyMessage(class UUMG_ChatMessage_C* Other);
	void SetMessage(const class FText& InText);
	void SetPlayer(bool Player1);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UMG_ChatMessage_C">();
	}
	static class UUMG_ChatMessage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUMG_ChatMessage_C>();
	}
};
static_assert(alignof(UUMG_ChatMessage_C) == 0x000008, "Wrong alignment on UUMG_ChatMessage_C");
static_assert(sizeof(UUMG_ChatMessage_C) == 0x000280, "Wrong size on UUMG_ChatMessage_C");
static_assert(offsetof(UUMG_ChatMessage_C, UberGraphFrame) == 0x000260, "Member 'UUMG_ChatMessage_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUMG_ChatMessage_C, ChatMessage) == 0x000268, "Member 'UUMG_ChatMessage_C::ChatMessage' has a wrong offset!");
static_assert(offsetof(UUMG_ChatMessage_C, PlayerName) == 0x000270, "Member 'UUMG_ChatMessage_C::PlayerName' has a wrong offset!");
static_assert(offsetof(UUMG_ChatMessage_C, isPlayer1) == 0x000278, "Member 'UUMG_ChatMessage_C::isPlayer1' has a wrong offset!");

}

