#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_CreateLocal

#include "Basic.hpp"

#include "PieceInfo_structs.hpp"


namespace SDK::Params
{

// Function UMG_CreateLocal.UMG_CreateLocal_C.ExecuteUbergraph_UMG_CreateLocal
// 0x0058 (0x0058 - 0x0000)
struct UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChecked_ReturnValue;                    // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFPSChessGameInstance_C*                K2Node_DynamicCast_AsFPSChess_Game_Instance;       // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPieceInfo                             CallFunc_Array_Get_Item;                           // 0x002C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPieceInfo                             K2Node_MakeStruct_PieceInfo;                       // 0x0044(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChecked_ReturnValue_1;                  // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal) == 0x000008, "Wrong alignment on UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal");
static_assert(sizeof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal) == 0x000058, "Wrong size on UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, EntryPoint) == 0x000000, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::EntryPoint' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, Temp_int_Array_Index_Variable) == 0x000004, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_IsChecked_ReturnValue) == 0x000010, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_IsChecked_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_GetGameInstance_ReturnValue) == 0x000018, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, K2Node_DynamicCast_AsFPSChess_Game_Instance) == 0x000020, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::K2Node_DynamicCast_AsFPSChess_Game_Instance' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_Array_Get_Item) == 0x00002C, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_Array_Length_ReturnValue) == 0x00003C, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, K2Node_MakeStruct_PieceInfo) == 0x000044, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::K2Node_MakeStruct_PieceInfo' has a wrong offset!");
static_assert(offsetof(UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal, CallFunc_IsChecked_ReturnValue_1) == 0x000054, "Member 'UMG_CreateLocal_C_ExecuteUbergraph_UMG_CreateLocal::CallFunc_IsChecked_ReturnValue_1' has a wrong offset!");

}

